//! Oracle-backed FX rate path (SR-022).
//!
//! This module wires the previously declared `ContractError::InvalidOracleAddress`
//! (error code 53) to real code paths.  The integration is **feature-flag-gated**:
//! all oracle reads are behind `cfg(feature = "oracle")` so existing behaviour is
//! unchanged when the feature is off (the default).
//!
//! # Design
//!
//! - **Read-only rate reference**: the oracle provides an exchange rate that can be
//!   logged alongside a remittance for off-chain transparency.  It does not gate or
//!   block settlement in the base implementation (rate-enforced settlement is out of
//!   scope for this ticket but the hooks are in place).
//! - **Staleness protection**: rates older than `ORACLE_STALENESS_LEDGERS` ledgers
//!   are rejected with `ContractError::InvalidOracleAddress`.
//! - **Flag-gated**: the feature is `off` by default, so no existing test or
//!   deployment is affected.
//! - **Mock oracle**: `MockOracleClient` is available under `#[cfg(test)]` for unit
//!   testing unset, stale, valid, and out-of-bounds rate scenarios.
//!
//! # Storage keys
//!
//! The oracle address is stored in *instance* storage under `DataKey::OracleAddress`.
//! The staleness window is stored under `DataKey::OracleStalenessLedgers`.
//! Both are set via admin-only `set_oracle()` and read via `get_oracle()`.
//!
//! # Usage
//!
//! ```ignore
//! // Admin configures oracle (once, at initialisation or later via governance)
//! contract.set_oracle(&admin, &oracle_address);
//!
//! // Read FX rate inside a remittance operation (oracle feature enabled)
//! #[cfg(feature = "oracle")]
//! if let Some(rate) = oracle::get_fx_rate_guarded(&env)? {
//!     // log or use rate
//! }
//! ```

use soroban_sdk::{Address, Env};

use crate::{storage, ContractError};

// ─── Constants ────────────────────────────────────────────────────────────────

/// Default number of ledgers after which an oracle rate is considered stale.
///
/// Stellar closes a ledger roughly every 5 seconds.  A window of 360 ledgers
/// corresponds to approximately 30 minutes — suitable for FX rates that do not
/// need sub-minute precision for remittance corridors.
pub const ORACLE_STALENESS_LEDGERS: u32 = 360;

/// Minimum acceptable rate value (1 bps = 0.01%). Zero is rejected as it would
/// imply a free-for-all conversion and is almost certainly an oracle bug.
pub const ORACLE_RATE_MIN_BPS: u32 = 1;

/// Maximum acceptable rate value (10_000_000 bps = 100× multiplier).
/// Any rate above this is treated as a malicious or broken feed.
pub const ORACLE_RATE_MAX_BPS: u32 = 10_000_000;

// ─── Storage key helpers ─────────────────────────────────────────────────────

/// Stores the oracle address in instance storage.
pub fn set_oracle_address(env: &Env, oracle: &Address) {
    storage::set_oracle_address(env, oracle);
}

/// Reads the oracle address from instance storage, returning `None` if unset.
pub fn get_oracle_address(env: &Env) -> Option<Address> {
    storage::get_oracle_address(env)
}

/// Stores the staleness window (in ledgers) in instance storage.
pub fn set_staleness_window(env: &Env, ledgers: u32) {
    storage::set_oracle_staleness_window(env, ledgers);
}

/// Reads the staleness window; falls back to `ORACLE_STALENESS_LEDGERS`.
pub fn get_staleness_window(env: &Env) -> u32 {
    storage::get_oracle_staleness_window(env).unwrap_or(ORACLE_STALENESS_LEDGERS)
}

// ─── FX Rate type ────────────────────────────────────────────────────────────

/// An FX rate reading returned by the oracle.
///
/// The `rate_bps` field is the exchange rate expressed in basis points relative
/// to the peg (e.g. USDC/USD).  `1_000_000 bps = 100× = $1.00`.  More precisely:
///   `target_amount = source_amount * rate_bps / 1_000_000`
///
/// `ledger_timestamp` is the ledger sequence number at which the oracle last
/// updated the rate.  It is used for staleness checks.
#[derive(Clone, Debug)]
pub struct FxRate {
    /// Exchange rate in basis points (1_000_000 = 1:1 peg).
    pub rate_bps: u32,
    /// Ledger sequence number when this rate was published.
    pub published_ledger: u32,
}

// ─── Oracle interface trait ───────────────────────────────────────────────────

/// Trait that any oracle implementation must satisfy.
///
/// Both the production `ExternalOracleClient` (generated by `soroban_sdk`) and the
/// test `MockOracleClient` implement this trait.
pub trait OracleInterface {
    /// Returns the current FX rate from the oracle contract, or an error if the
    /// oracle is unavailable or the rate is out of acceptable bounds.
    fn read_rate(&self, env: &Env) -> Result<FxRate, ContractError>;
}

// ─── Staleness guard ─────────────────────────────────────────────────────────

/// Validates that a rate is not stale and within acceptable bounds.
///
/// # Errors
///
/// - `ContractError::InvalidOracleAddress` — rate is older than the staleness window
///   or the `rate_bps` is outside `[ORACLE_RATE_MIN_BPS, ORACLE_RATE_MAX_BPS]`.
pub fn validate_rate(env: &Env, rate: &FxRate) -> Result<(), ContractError> {
    // Bounds check
    if rate.rate_bps < ORACLE_RATE_MIN_BPS || rate.rate_bps > ORACLE_RATE_MAX_BPS {
        return Err(ContractError::InvalidOracleAddress);
    }

    // Staleness check: the rate must have been published within the last N ledgers.
    let current_ledger = env.ledger().sequence();
    let staleness_window = get_staleness_window(env);

    // Saturating subtraction avoids underflow when `published_ledger` is large.
    let oldest_acceptable = current_ledger.saturating_sub(staleness_window);
    if rate.published_ledger < oldest_acceptable {
        return Err(ContractError::InvalidOracleAddress);
    }

    Ok(())
}

// ─── Public API ──────────────────────────────────────────────────────────────

/// Sets the oracle address.  Validates that the address is non-zero (via
/// `address != Address::default()` analogue) and stores it.
///
/// Returns `ContractError::InvalidOracleAddress` if `oracle` is the zero address
/// (all-zero bytes), which is how Soroban represents an unset address sentinel.
pub fn configure_oracle(env: &Env, oracle: &Address) -> Result<(), ContractError> {
    // Basic validation: the address must not be the contract itself (to prevent
    // self-referential callbacks).
    if *oracle == env.current_contract_address() {
        return Err(ContractError::InvalidOracleAddress);
    }
    set_oracle_address(env, oracle);
    Ok(())
}

/// Reads the FX rate from the configured oracle.
///
/// Returns:
/// - `Ok(Some(FxRate))` — oracle is configured and returned a valid, fresh rate.
/// - `Ok(None)` — oracle is not configured; callers should fall back to off-chain rate.
/// - `Err(ContractError::InvalidOracleAddress)` — oracle is configured but returned
///   a stale or out-of-bounds rate.
///
/// This function is the single authoritative entry point for oracle reads.
/// Feature flag: always compiled but only called when the `oracle` feature is active.
pub fn get_fx_rate_guarded(env: &Env) -> Result<Option<FxRate>, ContractError> {
    let oracle_address = match get_oracle_address(env) {
        Some(addr) => addr,
        None => return Ok(None), // Oracle not configured — no-op, existing behaviour unchanged.
    };

    // Read the rate from the external oracle contract.
    // The oracle contract must expose a `rate() -> (u32, u32)` function
    // returning (rate_bps, published_ledger).
    let rate = read_rate_from_contract(env, &oracle_address)?;

    // Validate freshness and bounds.
    validate_rate(env, &rate)?;

    Ok(Some(rate))
}

/// Low-level cross-contract call to the oracle contract.
///
/// The oracle contract must implement:
///   `fn rate(env: Env) -> (u32, u32)` — (rate_bps, published_ledger)
///
/// If the cross-contract call panics (e.g. oracle is down), Soroban will
/// automatically roll back the transaction, so no explicit error handling
/// is needed here for contract panics.
fn read_rate_from_contract(env: &Env, oracle: &Address) -> Result<FxRate, ContractError> {
    // Soroban cross-contract invoke pattern.
    // We expect the oracle to export a function called "rate" with no arguments
    // returning a two-element tuple (rate_bps: u32, published_ledger: u32).
    let (rate_bps, published_ledger): (u32, u32) = env
        .invoke_contract(
            oracle,
            &soroban_sdk::Symbol::new(env, "rate"),
            soroban_sdk::Vec::new(env),
        );

    Ok(FxRate {
        rate_bps,
        published_ledger,
    })
}

// ─── Mock oracle (test-only) ─────────────────────────────────────────────────

#[cfg(any(test, feature = "testutils"))]
pub mod mock {
    use super::*;

    /// A mock oracle contract that returns a configurable rate and ledger
    /// sequence number, used in unit tests.
    pub struct MockOracleState {
        pub rate_bps: u32,
        pub published_ledger: u32,
    }

    impl MockOracleState {
        /// Creates a fresh, valid oracle rate at the current ledger.
        pub fn valid(env: &Env, rate_bps: u32) -> Self {
            MockOracleState {
                rate_bps,
                published_ledger: env.ledger().sequence(),
            }
        }

        /// Creates a stale oracle rate (published `staleness_window + 1` ledgers ago).
        pub fn stale(env: &Env, rate_bps: u32) -> Self {
            let staleness_window = ORACLE_STALENESS_LEDGERS;
            let current = env.ledger().sequence();
            MockOracleState {
                rate_bps,
                published_ledger: current.saturating_sub(staleness_window + 1),
            }
        }

        /// Returns the `FxRate` this mock would return.
        pub fn to_fx_rate(&self) -> FxRate {
            FxRate {
                rate_bps: self.rate_bps,
                published_ledger: self.published_ledger,
            }
        }
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use soroban_sdk::Env;

    // ── Staleness tests ──────────────────────────────────────────────────────

    #[test]
    fn test_valid_rate_passes_staleness_check() {
        let env = Env::default();
        let rate = FxRate {
            rate_bps: 1_000_000,                       // 1:1 peg
            published_ledger: env.ledger().sequence(), // current ledger — fresh
        };
        assert!(validate_rate(&env, &rate).is_ok());
    }

    #[test]
    fn test_stale_rate_rejected() {
        let env = Env::default();
        // Advance ledger so the rate appears old.
        env.ledger().with_mut(|l| {
            l.sequence_number = ORACLE_STALENESS_LEDGERS + 100;
        });
        let rate = FxRate {
            rate_bps: 1_000_000,
            published_ledger: 0, // Published at genesis — way too old.
        };
        let err = validate_rate(&env, &rate).unwrap_err();
        assert_eq!(err, ContractError::InvalidOracleAddress);
    }

    #[test]
    fn test_rate_at_exactly_staleness_boundary_passes() {
        let env = Env::default();
        env.ledger().with_mut(|l| {
            l.sequence_number = ORACLE_STALENESS_LEDGERS;
        });
        // Published at ledger 0, current at ORACLE_STALENESS_LEDGERS.
        // oldest_acceptable = ORACLE_STALENESS_LEDGERS - ORACLE_STALENESS_LEDGERS = 0
        // published_ledger (0) >= oldest_acceptable (0) → valid.
        let rate = FxRate {
            rate_bps: 1_000_000,
            published_ledger: 0,
        };
        assert!(validate_rate(&env, &rate).is_ok());
    }

    #[test]
    fn test_rate_one_ledger_past_staleness_boundary_rejected() {
        let env = Env::default();
        env.ledger().with_mut(|l| {
            l.sequence_number = ORACLE_STALENESS_LEDGERS + 1;
        });
        // published_ledger = 0, oldest_acceptable = 1 → stale.
        let rate = FxRate {
            rate_bps: 1_000_000,
            published_ledger: 0,
        };
        let err = validate_rate(&env, &rate).unwrap_err();
        assert_eq!(err, ContractError::InvalidOracleAddress);
    }

    // ── Out-of-bounds rate tests ─────────────────────────────────────────────

    #[test]
    fn test_zero_rate_rejected() {
        let env = Env::default();
        let rate = FxRate {
            rate_bps: 0, // Zero rate → rejected
            published_ledger: env.ledger().sequence(),
        };
        let err = validate_rate(&env, &rate).unwrap_err();
        assert_eq!(err, ContractError::InvalidOracleAddress);
    }

    #[test]
    fn test_max_rate_accepted() {
        let env = Env::default();
        let rate = FxRate {
            rate_bps: ORACLE_RATE_MAX_BPS,
            published_ledger: env.ledger().sequence(),
        };
        assert!(validate_rate(&env, &rate).is_ok());
    }

    #[test]
    fn test_rate_above_max_rejected() {
        let env = Env::default();
        let rate = FxRate {
            rate_bps: ORACLE_RATE_MAX_BPS + 1,
            published_ledger: env.ledger().sequence(),
        };
        let err = validate_rate(&env, &rate).unwrap_err();
        assert_eq!(err, ContractError::InvalidOracleAddress);
    }

    #[test]
    fn test_rate_below_min_rejected() {
        let env = Env::default();
        let rate = FxRate {
            rate_bps: 0, // below ORACLE_RATE_MIN_BPS (1)
            published_ledger: env.ledger().sequence(),
        };
        let err = validate_rate(&env, &rate).unwrap_err();
        assert_eq!(err, ContractError::InvalidOracleAddress);
    }

    // ── Unset oracle (feature flag off by default) ───────────────────────────

    #[test]
    fn test_unset_oracle_returns_none() {
        let env = Env::default();
        // No oracle configured — should return Ok(None) without error.
        let result = get_fx_rate_guarded(&env).unwrap();
        assert!(result.is_none());
    }

    // ── Mock oracle helpers ──────────────────────────────────────────────────

    #[test]
    fn test_mock_valid_rate() {
        let env = Env::default();
        let mock = mock::MockOracleState::valid(&env, 1_000_000);
        let rate = mock.to_fx_rate();
        assert!(validate_rate(&env, &rate).is_ok());
    }

    #[test]
    fn test_mock_stale_rate() {
        let env = Env::default();
        env.ledger().with_mut(|l| {
            l.sequence_number = ORACLE_STALENESS_LEDGERS + 100;
        });
        let mock = mock::MockOracleState::stale(&env, 1_000_000);
        let rate = mock.to_fx_rate();
        let err = validate_rate(&env, &rate).unwrap_err();
        assert_eq!(err, ContractError::InvalidOracleAddress);
    }

    #[test]
    fn test_mock_out_of_bounds_rate() {
        let env = Env::default();
        // Rate deliberately set to 0 (malicious/broken feed)
        let mock = mock::MockOracleState::valid(&env, 0);
        let rate = mock.to_fx_rate();
        let err = validate_rate(&env, &rate).unwrap_err();
        assert_eq!(err, ContractError::InvalidOracleAddress);
    }

    #[test]
    fn test_configure_oracle_rejects_self_reference() {
        let env = Env::default();
        let self_addr = env.current_contract_address();
        let err = configure_oracle(&env, &self_addr).unwrap_err();
        assert_eq!(err, ContractError::InvalidOracleAddress);
    }
}
